# fly.toml app configuration file generated for customer-server on 2024-11-11T06:20:40+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'customer-server'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
